# Generated by Django 4.0.5 on 2022-09-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('time_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('code', models.CharField(max_length=128, verbose_name='权限代码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='权限名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='权限描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('time_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('code', models.CharField(db_index=True, max_length=128, verbose_name='角色代码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('permissions', models.ManyToManyField(blank=True, to='account.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('time_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='系统代码')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '系统模块',
                'verbose_name_plural': '系统模块',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=256, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮箱')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='激活')),
                ('is_superuser', models.BooleanField(blank=True, default=False, verbose_name='超级用户')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='可登录admin')),
                ('nick_name', models.CharField(blank=True, max_length=60, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='头像')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='secret', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('can_view', models.BooleanField(blank=True, default=False, verbose_name='能访问')),
                ('is_deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('roles', models.ManyToManyField(blank=True, to='account.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('time_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='团队代码')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='团队名称')),
                ('logo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='配置')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='状态')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.user', verbose_name='拥有者')),
                ('users', models.ManyToManyField(blank=True, to='account.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.system', verbose_name='系统'),
        ),
        migrations.AddField(
            model_name='role',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.team', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='permission',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='account.system', to_field='code', verbose_name='系统模块'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('system', 'code')},
        ),
    ]
