# Generated by Django 4.1.3 on 2022-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='删除')),
                ('time_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='作者')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, max_length=6, null=True, verbose_name='价格')),
                ('store', models.IntegerField(blank=True, default=0, verbose_name='库存')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('time_deleted', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
